import { c as create_ssr_component, e as each } from "../../chunks/ssr.js";
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return `${$$result.head += `<!-- HEAD_svelte-rnypo9_START -->${$$result.title = `<title>Buyer — PoshPOULE</title>`, ""}<!-- HEAD_svelte-rnypo9_END -->`, ""} <section class="relative overflow-hidden" data-svelte-h="svelte-ert4ct"><div class="mx-auto max-w-6xl px-4 py-12 md:py-16"><div class="grid md:grid-cols-2 gap-8 items-center"><div><h1 class="text-3xl md:text-4xl font-bold tracking-tight">Farm‑fresh poultry, delivered when you need it</h1> <p class="mt-3 text-gray-600">Order premium eggs and chicken from PoshPOULE Farms. Simple checkout, status updates, and proof of payment upload.</p> <div class="mt-6 flex gap-3"><a href="#shop" class="inline-flex items-center justify-center rounded bg-emerald-600 px-4 py-2 text-white hover:bg-emerald-700">Shop now</a> <a href="/about" class="inline-flex items-center justify-center rounded border px-4 py-2 hover:border-emerald-600 hover:text-emerald-700">Learn more</a></div></div> <div class="hidden md:block"><div class="aspect-video rounded-xl bg-gradient-to-br from-emerald-50 to-white border flex items-center justify-center"><div class="text-emerald-700 font-semibold">PoshPOULE</div></div></div></div></div></section> <section id="shop" class="max-w-6xl mx-auto px-4 pb-12"><div class="flex items-center justify-between" data-svelte-h="svelte-q530em"><h2 class="text-xl font-semibold">Shop Products</h2> <a href="/orders/stub-new" class="text-sm text-emerald-700 hover:underline">View my orders</a></div> ${`<div class="grid md:grid-cols-3 gap-4 mt-4">${each(Array(6), (_) => {
    return `<div class="border rounded p-3 animate-pulse" data-svelte-h="svelte-1j3vfg7"><div class="h-4 bg-gray-200 rounded w-2/3"></div> <div class="h-4 bg-gray-100 rounded w-1/3 mt-2"></div> <div class="h-8 bg-gray-100 rounded w-full mt-4"></div> </div>`;
  })}</div>`}</section>`;
});
export {
  Page as default
};
