version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: poshpoule-db
    environment:
      POSTGRES_USER: poshpoule
      POSTGRES_PASSWORD: poshpoule123
      POSTGRES_DB: poshpoule
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U poshpoule -d poshpoule"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
